# Generated by Django 2.2.15 on 2020-08-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprops',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
